service: tensorflow-lite-on-aws-lambda

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  versionFunctions: false

  ecr:
    images:
      tf-lite:
        path: ./

functions:
  predict:
    image:
      name: tf-lite
      command:
        - handler.predict