service: tensorflow-lite-on-aws-lambda

frameworkVersion: '2'

provider:
  name: aws
  lambdaHashingVersion: 20201221
  ecr:
    images:
      appimage:
        path: ./

functions:
  hello:
    image:
      name: appimage
